### PR TITLE
If Undertale's TTFFonts has its own things...

### PR DESCRIPTION
**Pull request by BreakinBenny**
...then I may as well just include a _separate_ TTFFonts.csx specifically for Deltarune. Do what you want with it.

### CODE REVIEW

**Comment by krzys-h** [comment]
Related: #40

Does this even work properly? If I remember correctly, Deltarune has a totally different order of the fonts, AND it uses font_add_sprite_something itself for the damage font, breaking the hacky assumption about font IDs that made the original script work.

**Comment by BreakinBenny** [comment]
Besides Noelle's "tiny Noelle" text not being shown, the normal text in the light world (and during CONTACT) works well if you also discount the dialogue choices being lower positioned lower on the Y axis than usual

The text during the Legend also works it uses the same programming (and fonts, by extension, I think). The answer is there for a yes, and a no.

**Comment by krzys-h** [comment]
Yeah... the script is supposed to reproduce the original fonts 100%. It worked like that in Undertale.

**Comment by Grossley** [comment]
It's fine to merge this, but this script will be added to the Experimental Scripts since it has not been tested thoroughly.

**Pull request merged**
