### PR TITLE
Fixed the EventType enum

### PR DESCRIPTION
**Pull request by minirop**
I set the correct name for the last 3 values of the EventType enum.

### CODE REVIEW

**Comment by Kneesnap** [comment]
Where did you get these names? Are they correct in both GMSv1 and GMSv2? Looks good, I just want to be sure this is only applicable to some versions.

**Comment by Grossley** [comment]
It's my understanding that these names are for GMS2 and that those are correct for GMS2. But I am unsure if those are also correct for GMS1.

**Comment by minirop** [comment]
@Kneesnap I didn't thought of GMS1, my bad. I got them by looking at the filename of scripts in my project (and confirmed it by compiling GM:S2 itself).

**Comment by minirop** [comment]
I looked again and made a small mistake, 11 is `Trigger` and not `Async` (since it is in `Other`). And those 3 new values don't exist in GMS1.
Also the sub event types for 'Gesture' are as follow (trigger and cleanup don't seem to have a subtype):
```
TAP = 0;
DOUBLE_TAP = 1;
DRAG_START = 2;
DRAG_MOVE = 3;
DRAG_END = 4;
FLICK = 5;
PINCH_START = 6;
PINCH_IN = 7;
PINCH_OUT = 8;
PINCH_END = 9;
ROTATE_START = 10;
ROTATING = 11;
ROTATE_END = 12;
GLOBAL_TAP = 64;
GLOBAL_DOUBLE_TAP = 65;
GLOBAL_DRAG_START = 66;
GLOBAL_DRAG_MOVE = 67;
GLOBAL_DRAG_END = 68;
GLOBAL_FLICK = 69;
GLOBAL_PINCH_START = 70;
GLOBAL_PINCH_IN = 71;
GLOBAL_PINCH_OUT = 72;
GLOBAL_PINCH_END = 73;
GLOBAL_ROTATE_START = 74;
GLOBAL_ROTATING = 75;
```

**Comment by minirop** [comment]
I fixed the enum and added the gesture subtype

**Comment by colinator27** [comment]
Merging as part of a two-PR merge

**Pull request merged**
