### PR TITLE
Make error on load show on UI thread

### PR DESCRIPTION
**Pull request by Miepee**
## Description
Makes it so errors on loading a data.win file are invoked on the UI thread and don't freeze the program.

### Caveats
None

### Notes
Addresses the issue #984 brought up.

### CODE REVIEW

**Comment by him7778** [comment]
Snipaste_2022-06-16_23-12-35
It still has problems.

**Comment by Miepee** [comment]
I wasn't saying i fixed the game loading.
I was saying, that I fixed the problem your issue *brought up*. Which is that the message boxes didn't appear.

**Comment by him7778** [comment]
> I wasn't saying i fixed the game loading. I was saying, that I fixed the problem your issue _brought up_. Which is that the message boxes didn't appear.

So sorry,is there a solution to this problem currently?

**Comment by Miepee** [comment]
You need to wait until #945 gets implemented. Which this PR does not do.

**Comment by Miepee** [comment]
Obsoleted in favour of #987 for now.

**Pull request closed without merging**
