### PR TITLE
Ensure layers ids are not duplicated.

### PR DESCRIPTION
**Pull request by BenjaminUrquhart**
See #355

### CODE REVIEW

**Comment by colinator27** [comment]
The only problem I guess now would be modifying layers with scripts, which wouldn't increment the counter. Maybe it should be re-evaluated every time, which hopefully wouldn't be too costly for performance since it's only a few hundred iterations.

**Comment by BenjaminUrquhart** [comment]
That's true.

**Comment by BenjaminUrquhart** [comment]
That's true. Should I move the code to the editor then?

**Comment by BenjaminUrquhart** [comment]
Thinking about it, I don't see people adding a bunch of layers by hand anyway so the potential performance impact shouldn't matter as much.

**Comment by colinator27** [comment]
I think it should be fine to move that to the editor, yeah

**Pull request merged**
